UserApp/urls.py
from django.urls import path

from UserApp import views
app_name='axfuser'

urlpatterns=[

    path('register/',views.register,name='register'),
    path('login/',views.login,name='login'),
    # 注册的后端验证
    path('checkName/',views.checkName,name='checkName'),
    # 发送邮件 邮件的格式修改
    path('sendemail/',views.sendemail),
    # 邮件的激活 扩展https=http+ssl（安全套接层）
    path('account/',views.account),

    # 登录
    path('getcode/',views.get_code),

]

axf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('axfhome/',include('AxfHomeApp.urls',namespace='axfhome')),
    path('axfmarket/',include('MarketApp.urls',namespace='axfmarket')),
    path('axfcart/',include('CartApp.urls',namespace='axfcart')),
    path('axfmine/',include('MineApp.urls',namespace='axfmine')),
    path('axfuser/',include('UserApp.urls',namespace='axfuser')),
]

templates/axf/user/register/active.html
尊敬的{{ name }}会员您好：
    恭喜获得奖品美女100
    现金一个亿
    详情请点击 <a href="{{ url }}">天堂的入口</a>
    或者复制连接{{ url }}去浏览器访问

templates/axf/user/register/register.html
{% extends 'base_user.html' %}
{% load static %}
{% block title %}
    {{ block.super }}
    注册
{% endblock %}
{% block ext_js %}
{{ block.super }}
    <script type="text/javascript" src="{% static 'axf/user/register/register.js' %}"></script>
{% endblock %}
{% block content %}
    {{ block.super }}
        <div class="container">
        <form action="{% url 'axfuser:register' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label for="exampleInputName">用户名</label>
            <input type="text" class="form-control" name="name" id="exampleInputName" placeholder="英文字母3到6个">
            <span id="nameinfo"></span>
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">邮箱</label>
            <input type="email" class="form-control" name="email" id="exampleInputEmail1" placeholder="请输入你的邮箱">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword1">密码</label>
            <input type="password" class="form-control" name="password" id="exampleInputPassword1" placeholder="请输入密码">
        </div>
        <div class="form-group">
            <label for="exampleInputPassword2">确认密码</label>
            <input type="password" class="form-control" id="exampleInputPassword2" placeholder="再次输入密码">
            <span id="passwordinfo"></span>
        </div>
        <div class="form-group">
            <label for="exampleInputFile">头像</label>
            <input type="file" name="icon" id="exampleInputFile">
            <p class="help-block">Example block-level help text here.</p>
        </div>
        <button type="submit" class="btn btn-success btn-block" style="color: darkgreen">注册</button>
    </form>
        </div>
{% endblock %}