AxfHomeApp/urls.py
from django.urls import path

from AxfHomeApp import views
app_name='axfname'

urlpatterns=[
    path('index/',views.index),
    path('home/',views.home,name='home'),


]

CartApp/urls.py
from django.urls import path

from CartApp import views
app_name='axfcart'
urlpatterns=[
    path('cart/',views.cart,name='cart'),
]

MarketApp/urls.py
from django.urls import path

from MarketApp import views
app_name='axfmarket'

urlpatterns=[
    path('index/',views.index),
    path('market/',views.market,name='market'),
]

MineApp/urls.py
from django.urls import path

from MineApp import views
app_name='axfmine'

urlpatterns=[
    path('mine/',views.mine,name='mine'),
]

axf/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('axfhome/',include('AxfHomeApp.urls',namespace='axfhome')),
    path('axfmarket/',include('MarketApp.urls',namespace='axfmarket')),
    path('axfcart/',include('CartApp.urls',namespace='axfcart')),
    path('axfmine/',include('MineApp.urls',namespace='axfmine')),
    path('axfuser/',include('UserApp.urls',namespace='axfuser')),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>
        {% block title %}
    
        {% endblock %}
    </title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/reset.css' %}">
{% block ext_css %}

{% endblock %}
</head>
<body>

{% block header %}

{% endblock %}
{% block content %}

{% endblock %}
{% block footer %}

{% endblock %}
<script type="text/javascript" src="{% static 'js/jquery.js' %}"></script>
<script type="text/javascript" src="{% static 'js/base.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.js' %}"></script>
{% block ext_js %}

{% endblock %}




</body>
</html>

templates/base_main.html
{% extends 'base.html' %}
{% load static %}
{# 根据css推测出html页面 #}
{% block ext_css %}
{{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/main/css/main.css' %}">
{% endblock %}
{% block header %}
{{ block.super }}

<header></header>
{% endblock %}

{% block footer %}
{{ block.super }}
<footer>
    <a href="{% url 'axfhome:home' %}">

    <dl class="home">


        <dt>
            <span></span>
        </dt>
        <dd>首页</dd>
    </dl>


    </a>
    <a href="{% url 'axfmarket:market' %}">

    <dl class="market">


        <dt>
            <span></span>
        </dt>
        <dd>闪购</dd>
    </dl>


    </a>
    <a href="{% url 'axfcart:cart' %}">

    <dl class="cart">


        <dt>
            <span></span>
        </dt>
        <dd>购物车</dd>
    </dl>


    </a>
    <a href="{% url 'axfmine:mine' %}">

    <dl class="mine">


        <dt>
            <span></span>
        </dt>
        <dd>我的</dd>
    </dl>


    </a>
</footer>
{% endblock %}

templates/base_user.html
{% extends 'base.html' %}
{% load static %}
{% block ext_css %}
{{ block.super }}
    <link rel="stylesheet" href="{% static 'axf/user/css/user.css' %}">
{% endblock %}
{% block header %}
<header></header>
{% endblock %}
{% block ext_js %}
{{ block.super }}
    <script type="text/javascript" src="{% static 'axf/user/js/md5.js' %}"></script>
{% endblock %}